language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
script:
  - pip install .
  - cd tests && python3 -m pytest

before_deploy:
  - cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQC1ADiu5WtD9UZiAJPQF/hObQBoNggzluPE2WblfBMv+fmxnzQPzTLM7SEWfUZWR2PJrQ9SSOejrT8dhqmuKjSPPebFCzxksTVwD29PPx4Fmfk/uaD8BVWqbzIfzHF4KUGr/GFWB2CGOiHvLqW/lLpoio2Birm5SCPlFkt0gqpMTMVGcjkBIQoOU5n4OMUgiU3ciTbb6+xhf3t3//d3mFJpBNeGHLeCahE74YscYjhQP3Vmi5q7kqNbe5rP3ON4Mq64CMRFtJ9tDDsWaka4CHuhC75H1SgUxyetJShVCanTljot/w/GhM/eHyOWFXJ1azFRp7PtfFodnyY7UddkeboGTNbOQvpEOFUjFuuCPYGWAXp6I6QoKsJj2gv0eM7oDct1tzckgOIB8q7Zsjb97tlqYAXaQ2FIaxEeveDMYoNOyOni34tXePI4XX0g/oCSPwajbyz6Efdtfc6LOrGnV+YeygjtRAsiBAGD5yWE7prqocxAGZeNHae4aYorsLM1sYzNCAmkGUTYOpiy/ZUGpqbGApJPn0QGs5lljX+eY5HBVKEujA4ESwlCBln2tRC5p6FcZRgu/52qKuJgcLa67cPu5LpxX3Gu4PflokJbLN5fgnmBKRiaCjt2XAu/yydjZmHPbJZ1elEpPP7De67qn6A5rzeXk32itgyc9DIqtti56Q
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
