os:
  - linux
  - windows
language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
script:
  - pip install .
  - cd tests && python3 -m pytest

